### ISSUE TITLE
ReactJS components are not rendering in AJAX

### ISSUE THREAD

**Issue by thangam105** [ishanjain28/Weather-App#1]
Hi,

I have used the AJAX for load the ReactJS components html file.But that components are not rendering.

How to achieve this?

Regards,
Thangavel E

**Comment by ishanjain28** [comment]
Can you clarify this? 
1. Which file are you trying to load? 
2. Do you see any error in Console? 

Please note that this project is not complete. I am trying to make a full fledged app and I got lost in Data flow of the app. I plan on recreating it from scratch. 

This is why I deleted all the previous commits.

**Comment by thangam105** [comment]
Thanking you for reply.

I have created that issues in babel and explained clearly.
https://phabricator.babeljs.io/T7569

Please suggestion needful..

**Comment by ishanjain28** [comment]
I have to close this issue because it is not related to this project. 

tip: Don't try to load whole components with ajax. Create a template and fill it with data from ajax. 
Also, to style an element in JSX you should do style={{width: 500px;}} and not style="width:500px;".
